#version 450

struct Intersection {
    vec4 color;
};

layout(set = 0, binding = 0, rgba8) uniform restrict writeonly image2D img;

layout(set = 1, std430, binding = 0) buffer restrict readonly Intersections {
    Intersection intersections[800][800][12];
};


void main() {

    vec4 result = intersections[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y][0].color;


    imageStore(img, ivec2(gl_GlobalInvocationID.xy ), result);

}