#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) buffer Model {
    mat4 transform;
};

layout(binding = 1) buffer restrict readonly VertexIn {
    vec4 vertexIn[];
};

layout(binding = 2) buffer restrict writeonly VertexOut {
    vec4 vertexOut[];
};

void main() {

    vertexOut[gl_GlobalInvocationID.x] = transform * vertexIn[gl_GlobalInvocationID.x];

}

